#!/bin/bash

RUN=0
BUILD=0
SETUP=0
MODE="none"

function build {
	if [ $BUILD -eq 1 ]; then
		make
	fi
}

cd "$(dirname "$0")"

for ((i=1;i<=$#;i++)); do
	if [ ${!i} = "setup" ]; then
		SETUP=1
	elif [ ${!i} = "build" ]; then
		BUILD=1
	elif [ ${!i} = "run" ]; then
		RUN=1
	elif [ ${!i} = "release" ]; then
		MODE="release"
	elif [ ${!i} = "debug" ]; then
		MODE="debug"
	fi
done;

if [ ${SETUP} -eq 1 ]; then
	mkdir debug > /dev/null 2>&1
	cd debug
	cmake -DCMAKE_BUILD_TYPE=Debug ../src
	cd ..
	mkdir release > /dev/null 2>&1
	cd release
	cmake -DCMAKE_BUILD_TYPE=Release ../src
	cd ..
fi

if [ ${MODE} = "debug" ]; then
	cd debug
	build
	if [ ${RUN} -eq 1 ]; then
		export vblank_mode=0
		export MESA_DEBUG="context"
		export LIBGL_DEBUG=1
		export GALLIUM_HUD="cpu+GPU-load;.dfps;VRAM-usage"

		./squareGame
	fi
elif [ ${MODE} = "release" ]; then
	cd release
	build
	if [ ${RUN} -eq 1 ]; then
		./squareGame
	fi
elif [ ${SETUP} -eq 0 ]; then
	echo "Invalid mode, use \"debug\" or \"release\""
fi

