#!/usr/bin/env bash

RUN=0
BUILD=0
SETUP=0
MODE="none"

function build {
	if [ $BUILD -eq 1 ]; then
		echo "Building mode \"${MODE}\"..."
		rm squareGame > /dev/null 2>&1
		make -j$(nproc)
	fi
}

cd "$(dirname "$0")"

for ((i=1;i<=$#;i++)); do
	if [ ${!i} = "setup" ]; then
		SETUP=1
	elif [ ${!i} = "build" ]; then
		BUILD=1
	elif [ ${!i} = "run" ]; then
		RUN=1
	elif [ ${!i} = "release" ]; then
		MODE="release"
	elif [ ${!i} = "debug" ]; then
		MODE="debug"
	fi
done;

if [ ${SETUP} -eq 1 ]; then
	ADD_BULLET_INSTALL="-DUSE_INSTALLED_BULLET="
	ADD_GLFW_INSTALL="-DUSE_INSTALLED_GLFW="

	echo "Use installed bullet?"
	select INSTALLED_BULLET in "Yes" "No"; do
		case ${INSTALLED_BULLET} in
			Yes) ADD_BULLET_INSTALL="${ADD_BULLET_INSTALL}ON"; break;;
			No) ADD_BULLET_INSTALL="${ADD_BULLET_INSTALL}OFF"; break;;
		esac
	done

	if [ "${INSTALLED_BULLET}" = "No" ]; then
		read -p "Enter bullet directory: " BULLET_DIR
		ADD_BULLET_INSTALL="${ADD_BULLET_INSTALL} -DBULLET_DIR=${BULLET_DIR}"
	fi

	echo "Use installed glfw?"
	select INSTALLED_GLFW in "Yes" "No"; do
		case ${INSTALLED_GLFW} in
			Yes) ADD_GLFW_INSTALL="${ADD_GLFW_INSTALL}ON"; break;;
			No) ADD_GLFW_INSTALL="${ADD_GLFW_INSTALL}OFF"; break;;
		esac
	done

	if [ "${INSTALLED_GLFW}" = "No" ]; then
		read -p "Enter glfw directory: " GLFW_DIR
		ADD_GLFW_INSTALL="-DGLFW_DIR=${GLFW_DIR}"
		ADD_GLFW_INSTALL="${ADD_GLFW_INSTALL} -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_INSTALL=OFF"
	fi

	read -p "Enter freetype 2 include directory: " FREETYPE_DIR
	read -p "Enter tbb include directory: " TBB_INCLUDE
	read -p "Enter tbb library directory: " TBB_LIB

	CMAKE_VARS="${ADD_BULLET_INSTALL} ${ADD_GLFW_INSTALL} -DFREETYPE_INCLUDE_DIR=${FREETYPE_DIR} -DBULLET2_TBB_INCLUDE_DIR=${TBB_INCLUDE} -DBULLET2_TBB_LIB_DIR=${TBB_LIB}"

	echo "Setting up debug directory..."
	mkdir debug > /dev/null 2>&1
	cd debug
	cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${CMAKE_VARS} ../src
	cd ..

	echo "Setting up release directory..."
	mkdir release > /dev/null 2>&1
	cd release
	cmake -DCMAKE_BUILD_TYPE=Release ${CMAKE_VARS} ../src
	cd ..
	echo "Setup complete."
fi

if [ ${MODE} = "debug" ]; then
	cd debug
	build
	if [ ${RUN} -eq 1 ]; then
		export vblank_mode=0
		export MESA_DEBUG="context"
		export GALLIUM_HUD="cpu+GPU-load;.dfps;VRAM-usage"

		./squareGame
	fi
elif [ ${MODE} = "release" ]; then
	cd release
	build
	if [ ${RUN} -eq 1 ]; then
		export GALLIUM_HUD="cpu+GPU-load;.dfps;VRAM-usage"
		./squareGame
	fi
elif [ ${SETUP} -eq 0 ]; then
	echo "Invalid mode, use \"debug\" or \"release\""
fi

